
CREATE TABLE `api_definition_his` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `group_code` varchar(31) NOT NULL DEFAULT '' COMMENT 'API 分组编码',
  `api_code` varchar(31) NOT NULL DEFAULT '' COMMENT 'API 编码',
  `api_name` varchar(31) DEFAULT NULL COMMENT 'API 名称',
  `api_method` varchar(15) NOT NULL DEFAULT 'GET' COMMENT 'API 方法',
  `api_uri` varchar(127) NOT NULL DEFAULT '' COMMENT 'API 路径',
  `result_type` varchar(31) NOT NULL DEFAULT 'OBJECT' COMMENT '返回值类型,OBJECT/LIST/PAGE',
  `enable_flag` int DEFAULT 1 COMMENT '启用状态',
  `api_script` longtext COMMENT 'API 脚本',
  `api_script_count` longtext COMMENT 'API 脚本-COUNT',
  `hump_conversion_switch` int NOT NULL DEFAULT '1' COMMENT '驼峰转换开关',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(31) DEFAULT NULL COMMENT '创建人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` varchar(31) DEFAULT NULL COMMENT '更新人',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `version` int NOT NULL DEFAULT 0 COMMENT '版本号',
  `status` bigint unsigned NOT NULL DEFAULT 1 COMMENT 'status',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `group_code` (`group_code`) USING BTREE,
  KEY `api_code` (`api_code`) USING BTREE,
  KEY `api_uri` (`api_uri`) USING BTREE
) ENGINE=InnoDB COMMENT='API 定义 历史';
