server:
  port: 8080

spring:
  config:
    activate:
      on-profile: demo
  datasource:
    url: jdbc:mysql://database_host:3306/your_db_schema?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: your_database_username
    password: your_database_password
    druid:
      stat-view-servlet:
        enabled: true
        resetEnable: true
        allow: 0.0.0.0/0
      web-stat-filter:
        enabled: true
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: your_redis_password
      timeout: 3000

# mybatis:
#  configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
