server:
  port: 8080

spring:
  config:
    activate:
      on-profile: demo
  datasource:
    url: jdbc:mysql://database_host:3306/your_db_schema?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: your_database_username
    password: your_database_password


# mybatis:
#  configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
